ss_cms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from website.views import ArticleView, ArticleEditView, TocView, PageView, \
    ImageUpload, ImageBrowserView, ListImagesView, FileBrowserView, FileUpload, ListFilesView, ListPagesView, \
    NewArticleView, EditSettingsView, IndexView, GlobalContentView, DeleteGlobalContentView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


# Add this back to re-enable the admin side.
# path('admin/', admin.site.urls),


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.login, name='login'),
    path('accounts/logout/', auth_views.logout, name='logout'),
    url(r'accounts/resetpw/',auth_views.password_reset,
        {'post_reset_redirect' : '/accounts/resetpwdone/'},
        name="password_reset"),
    path(r'', PageView.as_view(), name="index"),
    path(r'home/', IndexView.as_view(), name="home"),
    path(r'imagebrowser/', ImageBrowserView.as_view(), name="imagebrowser"),
    url(r'^article/(?P<slug>[a-zA-Z0-9\-_]+)/$', ArticleView.as_view(), name="article"),
    url(r'^editArticle/(?P<slug>[a-zA-Z0-9\-_]+)/$', ArticleEditView.as_view(), name="edit_article"),
    url(r'^newArticle/$', NewArticleView.as_view(), name="new_article"),
    url(r'^toc/(?P<slug>[a-zA-Z0-9\-_]+)/$', TocView.as_view(), name="toc"),
    url(r'^page/(?P<slug>[a-zA-Z0-9\-_]+)/$', PageView.as_view(), name="page"),
    url(r'^imageupload/(?P<slug>[a-zA-Z0-9\-_]+)/$', ImageUpload.as_view(), name="imageupload"),
    url(r'^fileupload/(?P<slug>[a-zA-Z0-9\-_]+)/$', FileUpload.as_view(), name="fileupload"),
    url(r'^listimages/$', ListImagesView.as_view(), name="listimages"),
    url(r'^filebrowser/(?P<slug>[a-zA-Z0-9\-_]+)/$', FileBrowserView.as_view(), name="filebrowser"),
    url(r'^listfiles/$', ListFilesView.as_view(), name="listfiles"),
    url(r'^listpages/$', ListPagesView.as_view(), name="listpages"),
    url(r'^settings/$', EditSettingsView.as_view(), name="settings"),
    url(r'^globalcontent/(?P<id>[0-9]+)/$', GlobalContentView.as_view(), name="globalcontent"),
    url(r'^globalcontent/$', GlobalContentView.as_view(), name="globalcontent"),
    url(r'^deleteglobalcontent/(?P<id>[0-9]+)/$', DeleteGlobalContentView.as_view(), name="deleteglobalcontent"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models
from ss_cms.settings import BASE_DIR
from os import listdir
# Create your models here.


from django.contrib.auth.models import Group, User


def THEMES():
        files = listdir(BASE_DIR + "/website/templates/")
        themes = []
        for file in files:
            themes.append((file, file))
        return tuple(themes)


PAGETYPES = (
    ('article', 'Article'),
    ('link', 'Link'),
    ('index','Index')
)

class Article(models.Model):
    page_type = models.CharField(choices=PAGETYPES, max_length=32, default='article')
    title = models.CharField(max_length=1024, null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    header_image = models.ImageField(null=True, blank=True)
    slug = models.CharField(max_length=32, unique=True,
                            help_text="Must be one lowercase word. You must "
                                "populate either slug or link for proper functionality.")
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True, help_text="Anyone in this group "
                                                                                                "can edit.")
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE, blank=True, help_text="The owner can edit.")
    link = models.URLField(null=True, blank=True, help_text="Use to link to external sites. If used, the field 'slug' "
                                                            "is ignored.")
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE,
                               help_text="Optional. Used for menu or breadcrumb trail. Empty indicates top level.")
    order = models.IntegerField(default=0, help_text="For menu order. It is recommended that you use increments of 10 "
                                                     "as to allow for easy re-ordering of menu items. A value of 0 "
                                                     "indicates that it is not a menu item.")
    post_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title


class GlobalContent(models.Model):
    name = models.CharField(max_length=32)
    content = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "GlobalContent"


class Image(models.Model):
    image_name = models.CharField(max_length=32)
    image_location = models.CharField(max_length=1024)
    image_key = models.CharField(max_length=32)

    def __str__(self):
        return self.image_name


class Settings(models.Model):

    site_name = models.CharField(max_length=32, blank=True, null=True)
    site_tag_line = models.CharField(max_length=1024, blank=True, null=True)
    www_root = models.URLField(max_length=1024, help_text="This is the location where your site is located."
                                                          "http://www.example.com")
    home_page = models.ForeignKey(Article, on_delete=models.CASCADE)
    theme = models.CharField(choices=THEMES(), max_length=32, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Settings"

    def __str__(self):
        return "Settings"

website/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView, View, FormView
from django.db.models import Q
from django.urls import reverse
from .models import Article, GlobalContent, Settings as SiteSettings

from .forms import ArticleForm, NewArticleForm, SettingsForm, GlobalContentForm
from django.shortcuts import get_object_or_404, redirect
from braces.views import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import Group, User
import pprint, ss_cms.settings as Settings
import boto3, re
from django.http import JsonResponse, HttpResponse
from PIL import Image
import tempfile
from storages.backends.s3boto3 import S3Boto3Storage
import tempfile
import os


# Create your views here




class MyArticleMixin(object):
    #
    # Parent Class Only
    #

    def get_context_data(self, *args, **kwargs):
        context = super(MyArticleMixin, self).get_context_data(*args, **kwargs)
        context['menu'] = get_menu()
        context['can_edit'] = False
        page_group = None
        if 'slug' in self.kwargs:
            article = get_object_or_404(Article, slug=self.kwargs['slug'])
            if Article.objects.filter(parent=article).exists():
                children = Article.objects.filter(parent=article)
            else:
                children = None
            context['children'] = children
            siblings = Article.objects.filter(parent=article.parent)
            context['siblings'] = siblings.order_by('order')
            gcbs = GlobalContent.objects.all()
            if article.content is not None:
                for gcb in gcbs:
                    article.content = article.content.replace("{{ " + gcb.name + " }}", gcb.content)
                context['article'] = article
            page = get_object_or_404(Article, slug=self.kwargs['slug'])
            page_group = page.group
            context['slug'] = self.kwargs['slug']
            context['breadcrumbs'] = get_breadcrumbs(page.id)
            if self.request.user == Article.objects.get(slug=self.kwargs['slug']).owner or \
                self.request.user == Article.objects.get(slug=self.kwargs['slug']).owner or \
                self.request.user.groups.filter(name='editor').exists():
                    context['can_edit'] = True
                    context['slug'] = self.kwargs['slug']
        if page_group is not None:
            if self.request.user.groups.filter(id=page_group.id).exists():
                context['can_edit'] = True



        if self.request.user.is_superuser:
            context['can_edit'] = True
            context['is_admin'] = True

        global_content = {}
        contents = GlobalContent.objects.all()
        for content in contents:
            global_content[content.name] = content.content
        context['global_content'] = global_content
        context['site_settings'] = SiteSettings.objects.all()[0]
        return context


class IndexView(MyArticleMixin, TemplateView):
    template_name = "index.html"


class GlobalContentView(UserPassesTestMixin, MyArticleMixin, FormView):
    template_name = "global_content.html"
    form_class = GlobalContentForm

    def test_func(self, user):
        return user.is_superuser

    def form_valid(self, form):
        self.success_url = reverse('globalcontent')
        if form['id'].value() == '':
            gcb = GlobalContent()
        else:
            gcb = GlobalContent.objects.get(id=form['id'].value())
        gcb.name = form['name'].value()
        gcb.content = form['content'].value()
        gcb.save()
        return super(GlobalContentView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(GlobalContentView, self).get_context_data(*args, **kwargs)
        gcbs = GlobalContent.objects.all()
        context['globals'] = gcbs
        if 'id' in self.kwargs:
            context['id'] = self.kwargs['id']
        return context

    def get_initial(self):
        initial = None
        if 'id' in self.kwargs:
            gcb = get_object_or_404(GlobalContent,id=self.kwargs['id'])
            initial = {
                'name': gcb.name,
                'content': gcb.content,
                'id': gcb.id,
            }
        return initial


class DeleteGlobalContentView(UserPassesTestMixin, RedirectView):
    def test_func(self, user):
        return user.is_superuser

    def get_redirect_url(self, *args, **kwargs):
        gcb = get_object_or_404(GlobalContent, id=self.kwargs['id'])
        gcb.delete()
        # gcb.save()
        self.url = reverse('globalcontent')
        return super(DeleteGlobalContentView, self).get_redirect_url(*args, **kwargs)


class PageView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):

        # If kwargs are empty, assume it is the home_page that we want.
        if 'slug' in self.kwargs:
            article = Article.objects.get(slug=self.kwargs['slug'])

        else:
            article = SiteSettings.objects.all()[0].home_page

        kwargs = {"slug" : article.slug}
        if article.page_type == 'table_of_contents':
            self.url = reverse('toc', kwargs=kwargs)
        if article.page_type == 'article':
            self.url = reverse('article', kwargs=kwargs)
        if article.page_type == 'link':
            self.url = Article.objects.get(slug=kwargs['slug']).link
        if article.page_type == 'index':
            self.url = reverse('home')

        return super(PageView, self).get_redirect_url(*args, **kwargs)


class ArticleView(MyArticleMixin, TemplateView):
    template_name = "generic.html"
    

class ArticleEditView(UserPassesTestMixin, MyArticleMixin, FormView):
    template_name = "edit_generic.html"
    raise_exeption = True
    form_class = ArticleForm

    def test_func(self, user):
        if 'slug' in self.kwargs:
            return has_edit_permission(user, self.kwargs['slug'])
        else:
            return user.is_superuser

    def form_invalid(self, form):
        return super(ArticleEditView, self).form_invalid(form)

    def form_valid(self, form):
        self.success_url = reverse('page', kwargs={'slug': form['slug'].value()})
        if Article.objects.filter(slug=form['slug'].value()).exists():
            article = Article.objects.get(slug=self.kwargs['slug'])
        else:
            article = Article()
        article.title = form['title'].value()
        article.summary = form['summary'].value()
        article.slug = form['slug'].value()
        article.content = form['content'].value()
        article.page_type = form['page_type'].value()
        article.group_id = form['group'].value()
        article.parent_id = form['parent'].value()
        article.order = form['order'].value()
        article.owner_id = form['owner'].value()
        article.header_image = form['header_image'].value()
        article.link = form['link'].value()
        article.save()
        return super(ArticleEditView, self).form_valid(form)

    def get_initial(self):
        initial = None
        if 'slug' in self.kwargs:
            article = Article.objects.get(slug=self.kwargs['slug'])
            initial = {
                "page_type": article.page_type,
                "title": article.title,
                "content": article.content,
                "summary": article.summary,
                "header_image": article.header_image,
                "slug": article.slug,
                "group": article.group,
                "owner": article.owner,
                "link": article.link,
                "parent": article.parent,
                "order": article.order
            }
        return initial


class NewArticleView(UserPassesTestMixin, MyArticleMixin, FormView):
    template_name = "new_article.html"
    raise_exeption = True
    form_class = NewArticleForm

    def test_func(self, user):
        return user.is_superuser


    def form_invalid(self, form):

        return super(NewArticleView, self).form_invalid(form)

    def form_valid(self, form):
        self.success_url = reverse('edit_article', kwargs={'slug': form['slug'].value()})
        article = Article()
        article.title = form['title'].value()
        article.slug = form['slug'].value()
        article.page_type = form['page_type'].value()
        if form['group'].value() != "":
            article.group_id = form['group'].value()
        if form['parent'].value() != "":
            article.parent_id = form['parent'].value()
        article.order = form['order'].value()
        article.owner_id = form['owner'].value()
        article.header_image = form['header_image'].value()
        article.link = form['link'].value()
        print(article)
        article.save()
        return super(NewArticleView, self).form_valid(form)

    def get_initial(self):
        initial = {
            "owner":self.request.user.id,
            "order":0
        }
        return initial


class TocView(MyArticleMixin, TemplateView):
    template_name = 'toc.html'

    def get_context_data(self, **kwargs):
        context = super(TocView, self).get_context_data(**kwargs)
        parent = get_object_or_404(Article, slug=kwargs['slug'])
        if Article.objects.filter(parent=parent).exists():
            children = Article.objects.filter(parent=parent)
        else:
            children = None
        context['children'] = children
        context['article'] = parent
        return context


class ImageBrowserView(MyArticleMixin, TemplateView):
    template_name = "image_browser.html"


class FileBrowserView(MyArticleMixin, TemplateView):
    template_name = "file_browser.html"


class ListImagesView(LoginRequiredMixin, View):

    def post(self, user):
        """
        This view returns the directory structure for everything under the 'dir' specified in the post request
        :return: HTML for the AJAX request
        """

        if self.request.POST['dir'] == '/':

website/templates/editorial/edit_generic.html
{% extends "layouts/homepage.html" %}
{% load staticfiles %}
{% block main %}
<!-- test comment -->


					<div id="main">
						<div class="inner">

							<!-- Header -->
								{% include "layouts/header.html" %}

							<!-- Content -->
								<section>
                                <form action="." method="post" class="edit_p">
                                    {% csrf_token %}
									{% autoescape off %}
									{{ form.as_p }}
									{% endautoescape %}<br />
                                    <button id="submit" type="submit">Update</button>
                                </form>
								</section>


						</div>
					</div>

<style>

/* ### Edit Page Changes ### */
#id_content_ifr {
    min-height: 500px;
}
.mce-content-body img {
    max-width: 100%;
}
section p:nth-child(-n+3) {
    width: 49%;
    display: inline-block;
    padding-right: 40px;
}
section p:nth-child(n+6) {
    width: 33%;
    display: inline-block;
    padding: 0 30px;
}

#submit {
    float:right;
}

/* Proposed Additions */
#id_order {
    position: relative;
}
#id_order:hover + .current_order, #id_order:active + .current_order {
    display: block;
}
.current_order {
    position: absolute;
    margin: -1px 1em;
    padding: 10px 30px 10px 10px;
    min-height: 100px;
    height: auto;
    font-size: 90% !important;
    border: 2px solid #e7e7e7;
    background: #f5f5f5;
    color: #494949;
}
.current_order > ul {
    list-style: none;
    padding-left: 15px !important;
    margin-bottom:1em !important;
}
.current_order > ul > li > span {
    font-size: 90% !important;
    font-style: italic;
}
.current_page {
    font-weight: bold;
    font-size: 110%;
}
li.current_page:before {
    content: "* ";
}
</style>

<script src="{% static "editorial/js/tinymce/tinymce.min.js" %}" ></script>
<script>
var id_order_width = $('#id_order').width();
console.log(id_order_width);
var current_order = '' +
    '<div class="current_order" style="display:none">' +
    '   <b>CURRENT ORDER</b>:\n' +
    '   <ul>\n' +
        {% for sibling in siblings %}
    '       <li{% if sibling.slug in request.path %} class="current_page"{% endif %}><span>{{ sibling.order }}</span> -- {{ sibling.title }}</li>\n' +
        {% endfor %}
    '   </ul>\n' +
{#    '   <p>\n' +#}
{#    '       Order is...\n' +#}
{#    '   </p>\n' +#}
    '</div>';
$('#id_order').after(current_order);
$("#id_order").hover(function(){
    $('.current_order').css('max-width',id_order_width);
    $('.current_order').fadeToggle().delay('1000');
});
$("#id_order").focus(function(){
    $('.current_order').css('max-width',id_order_width);
    $('.current_order').fadeToggle();
});

  tinymce.init({
      selector: '.editable',
      branding: false,
      plugins: 'image code link fullscreen lists',
      toolbar: ' formatselect | undo redo | bold italic | alignleft aligncenter alignright alignjustify | link image file | numlist bullist outdent indent | removeformat code fullscreen ',
      menubar: 'edit view insert format',
      image_dimensions: false,
      file_picker_types: 'file image media',
      verify_html: false,
      images_upload_handler: function(blobInfo, success, failure) {
          imageUploadHandler(blobInfo, success, failure);
      },
      file_upload_handler: function(blobInfo, success, failure) {
          imageUploadHandler(blobInfo, success, failure);
      },
      file_picker_callback: function(callback, value, meta){
              myFilePicker(callback, value, meta);
  }
});

function myFilePicker(callback, value, meta) {
    console.log(meta);

    if (meta.filetype == "image"){
        var url = "{% url 'imagebrowser' %}";
        var title = "Image Browser";
    }
    else{
        var url = "{% url 'filebrowser' slug %}";
        var title = "File Browser";
    }
    tinymce.activeEditor.windowManager.open({
        title: title,
        url: url,
        width: 650,
        height: 550,
    }, {
        oninsert: function (url) {
            console.log(url);
            callback(url);
        }
    });
}

function imageUploadHandler (blobInfo, success, failure) {
          console.log("Something went here");
          var xhr, formData;
          xhr = new XMLHttpRequest();
          xhr.withCredentials = false;
          xhr.open('POST', '{% url 'imageupload' slug %}');

          xhr.onload = function(){
              var json;
              if (xhr.status != 200) {
                  failure('HTTP Error: ' + xhr.status);
                  return;
              }
          json = JSON.parse(xhr.responseText);
          if (!json || typeof json.location != 'string') {
              failure('Invalid JSON: ' + xhr.responseText);
              return;
          }
          success(json.location);
      };
      formData = new FormData();
      formData.append('file', blobInfo.blob(), blobInfo.filename());
      formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
      xhr.send(formData);
}
</script>

{% endblock %}

website/templates/editorial/generic.html
{% extends "layouts/homepage.html" %}
{% load staticfiles %}
{% block main %}
					<div id="main">
						<div class="inner">

							<!-- Header -->
								{% include "layouts/header.html" %}

							<!-- Content -->
								<section>
									<header class="main">
									 <div id="editor">
										<h1>{{ article.title }}</h1>
                                         {% autoescape off %}
                                         <h2>{{ article.summary }}</h2>
                                         {%  endautoescape %}
									</div>
									</header>
                                    {% if article.header_image %}
									<img src="{{ article.header_image.url }}">
                                {% endif %}

									{% autoescape off %}
									<div id="mainContentEditor">	
										{{ article.content }}
									</div>
									{% endautoescape %}

								</section>

						</div>
					</div>

<script> 
</script>
{% endblock %}

website/templates/editorial/global_content.html
{% extends "layouts/homepage.html" %}
{% load staticfiles %}
{% block main %}
<!-- test comment -->


					<div id="main">
						<div class="inner">

							<!-- Header -->
								{% include "editorial/layouts/header.html" %}

							<!-- Content -->
								<section>
                                    {% if id %}
                                        <div>
                                        <form action="." method="post">
                                    {% else %}
                                        <div id="show-form" style="display:none">
                                        <h2>Create New</h2>
                                        <form action="." method="post">
                                    {% endif %}
                                            {% csrf_token %}
                                            {% autoescape off %}
                                                {{ form.as_p }}
                                            {% endautoescape %}<br />
                                            <button id="submit" type="submit">Submit</button>
                                        </form>
                                        <br />
                                        <hr />
                                    </div>
								</section>

                            <h2>
                                Global Content
                                {% if id %}
                                    <button class="btn btn-success new-gcb-page">Add New</button>
                                {% else %}
                                    <button class="btn btn-success new-gcb">Add New</button>
                                {% endif %}
                            </h2>
                            <table class="table table-hover footable metro-blue toggle-square-filled toggle-medium" data-sort="true">
                                <thead>
                                    <tr class="theader" style="text-align:center;">
                                        <th>ID</th>
                                        <th data-sort-initial="false">Name</th>
                                        <th>Content</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>
                                <tbody id="gcbs">
                                    {% for gcb in globals %}
                                        <tr>
                                            <td>{{ gcb.id }}</td>
                                            <td><a href="{% url 'globalcontent' gcb.id %}">{{ gcb.name }}</a></td>
                                            <td class="truncate">{{ gcb.content|truncatechars:128 }}</td>
                                            <td style="text-align:center">
                                                <a href="{% url 'deleteglobalcontent' gcb.id %}" title="Remove {{ gcb.name }}?" id="remove-gcb-id-{{ gcb.id }}">
                                                    <span class="icon fa-trash" style="color:red; font-size: 18px;"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
						</div>
					</div>


    <link href="{% static 'editorial/footable/footable.core.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'editorial/footable/footable.standalone.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'editorial/footable/footable.js' %}" type="text/javascript"></script>
    <script src="{% static 'editorial/footable/footable.sort.js' %}" type="text/javascript"></script>
    <script type="text/javascript">

{#        function showField(info) {#}
{#            document.getElementById('#hidden_div').innerHTML = document.getElementById('course-select').options[info].text;#}
{#        }#}
{##}


        $('.footable').footable({
            breakpoints: {
                phone: 480,
                tablet: 676
            }
        });

        $(function () {
            $('table').footable();

            $('.toggle').click(function () {
                $('.toggle').toggle();
                $('table').trigger($(this).data('trigger')).trigger('footable_redraw');
            });
        });
{#        $('tr').click(function () {#}
{#            window.location = $(this).find('a').attr('href');#}
{#        }).hover(function () {#}
{#            $(this).toggleClass('hover');#}
{#        });#}

        $(document).ready(function () {
{#            $('.course-select-spring').each(function () {#}
{#                $(this).html($.trim($(this).html()))#}
{#            });#}
{#            $('tbody:empty').parents('#commenttable').hide();#}

            url = document.location.href;
            hash = url.split('#');
            $('#show-'+hash[1]).toggle();
        });


    $('#id_title').on('change keyup paste', function(){
        $('#id_slug').val($('#id_title').val().replace(/ /g,'-').toLowerCase().replace(/[^\w\s-]/g,''))
    });

    $('.new-gcb').on('click', function(){
        $('#show-form').toggle(800);
    });

    $('.new-gcb-page').on('click', function(){
        window.location.href = "{% url 'globalcontent' %}#form";
    });

</script>

    <style>


/* ### Edit Page Changes ### */
    .new-gcb, .new-gcb-page {
        float:right;
        padding: 7px 15px;
        height: auto;
        line-height: 35px;
    }
    #id_content_ifr {
        min-height: 500px;
    }
    .mce-content-body img {
        max-width: 100%;
    }
    section p:nth-child(-n+2) {
        width: 48%;
        display: inline-block;
        padding-right: 40px;
    }

    #submit {
        float:right;
    }

    .truncate {
        width:90%;
        max-width: 400px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>

{% endblock %}

website/templates/editorial/index.html
{% extends "editorial/layouts/homepage.html" %}
{% load staticfiles %}
{% block main %}
    <div id="main">

						<div class="inner">

							<!-- Header -->
								{% include "editorial/layouts/header.html" %}


							<!-- Section -->
								<section>
									<header class="major">
										<h2>Site Sections</h2>
									</header>
									<div class="features">
										<article>
											<span class="icon fa-cogs"></span>
											<div class="content">
												<h3>Home Automation</h3>
												<p>IoT and home automation has come a long way in the last couple of years, but there are still needs for "hacks" and hombrew projects to fill the gaps and get everything working the way it should...</p>
											</div>
										</article>
										<article>
											<span class="icon fa-file-code-o"></span>
											<div class="content">
												<h3>Programming Projects</h3>
												<p>I write programs for fun, in-house business use and... well just to learn. These are the programs that I have worked on. I'm sure they are not all perfect but hey, life's a journey...</p>
											</div>
										</article>
										<article>
											<span class="icon fa-graduation-cap"></span>
											<div class="content">
												<h3>Tutorials</h3>
												<p>Sometimes I like to do tutorials and lessons to help others and to help me learn/remember what I am doing...</p>
											</div>
										</article>
										<article>
											<span class="icon fa-file-archive-o"></span>
											<div class="content">
												<h3>Catch all</h3>
												<p>This is where everything ends up that does not fit into one of the other catagories.</p>
											</div>
										</article>
									</div>
								</section>



						</div>
					</div>


{% endblock %}

website/templates/editorial/new_article.html
{% extends "layouts/homepage.html" %}
{% load staticfiles %}
{% block main %}
<!-- test comment -->


					<div id="main">
						<div class="inner">

							<!-- Header -->
								{% include "layouts/header.html" %}

							<!-- Content -->
								<section>
                                <form action="." method="post">
                                    {% csrf_token %}
									{% autoescape off %}
									{{ form.as_p }}
									{% endautoescape %}<br />
                                    <button id="submit" type="submit">New</button>
                                </form>
								</section>


						</div>
					</div>

<script>
    $('#id_title').on('change keyup paste', function(){
        $('#id_slug').val($('#id_title').val().replace(/ /g,'-').toLowerCase().replace(/[^\w\s-]/g,''))
    });
</script>

    <style>


/* ### Edit Page Changes ### */
    #id_content_ifr {
        min-height: 500px;
    }
    .mce-content-body img {
        max-width: 100%;
    }
    section p:nth-child(n+5) {
        width: 48%;
        display: inline-block;
        padding: 0 30px;
    }

    #submit {
        float:right;
    }

</style>

{% endblock %}